### ISSUE TITLE
Temporary Retryer does not report any error when aborting

### ISSUE THREAD

**Issue by Teelevision** [streadway/handy#36]
https://github.com/streadway/handy/blob/d5acb3125c2a6654d2d691e6851674a645333da1/retry/strategy.go#L95-L109

In line 104 the Temporary Retryer returns an Abort without any error.

If using the net/http package's Client with this retry Transport as http.RoundTripper, the Client will not handle this unexpected case where neither error nor response is returned, and cause a nil pointer dereference panic here: https://github.com/golang/go/blob/1dc0110bf725640a9b912e3d31e6654ed1c4da9d/src/net/http/client.go#L422

The Temporary Retryer should either return the original error or create a new error to return.

**Comment by Teelevision** [comment]
This is related: https://github.com/golang/go/issues/33563

**Comment by hazcod** [comment]
Suppose it's fixed now @Teelevision ?

**Comment by Teelevision** [comment]
> Suppose it's fixed now @Teelevision ?

No, it's not fixed. I opened #37 to address this issue.

**Comment by streadway** [comment]
Thanks for the report, can you confirm the fix works?

**Comment by Teelevision** [comment]
Yes, I can confirm, as we are using the version in the pull request for months now.
